language: python
python:
  - "3.5"

env:
  - DJANGO_VERSION=1.11.2

before_install:
  - export DJANGO_SETTINGS_MODULE=mysite.settings
  - export PYTHONPATH=$HOME/builds/fevsea/djangoTutorial
  - export PIP_USE_MIRRORS=true

install:
  - pip install django==$DJANGO_VERSION
  - cp mysite/secrets.py.template mysite/secrets.py

script:
  - python manage.py test -v 2

